name = Taks
description = razne taksativne stranice
template = taks-layout

; Regions
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[content] = Content
regions[lists] = Lists
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[footer] = Footer

; Styles
stylesheets[all][] = css/layouts/taks/taks.layout.css
stylesheets[all][] = css/layouts/taks/taks.layout.no-query.css

