<?php

/**
* Taken from here: 
* http://getlevelten.com/blog/randall-knutson/cron-queues-processing-large-amounts-data-cron
*/

/**
* Implementation of hook_cron_queue_info()
*/

function moj_cron_queue_cron_queue_info() {
    $queues['runner'] = array(
        'worker callback' => 'runner_run', // This is the callback function for each queue item.
        'time' => 180, // This is the max run time per cron run in seconds.
    );
    return $queues;
}

/** * Implementation of hook_cron() */
function moj_cron_queue_cron() {
    $items = array("Hello", "World"); // Put everything in a queue for processing.
    $queue = DrupalQueue::get('runner');
    foreach($items as $item) {
        $queue->createItem($item);
    }
} 

/**
* Worker Callback for the runner cron queue.
*/
function moj_cron_queue_run($item) {
    print $item;
} 

/**
* Odavde: http://drupal.stackexchange.com/questions/8956/in-a-custom-module-how-do-i-get-all-the-nodes-of-a-certain-type
*
* $query = db_query("SELECT nid FROM {node} WHERE type = '%s'", $type);
* 
*  while ($result = db_fetch_object($query)) {
*  $node = node_load($result->nid);
*   // Use $node or store it in an array;
* }
* 
* Odavde: https://api.drupal.org/api/examples/cron_example!cron_example.module/function/cron_example_queue_1_worker/7
*
* function cron_example_queue_1_worker($item) {
*   cron_example_queue_report_work(1, $item);
* }
*/

